# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 76793a56b664542bc3c7e9f374973d5d1e9a0e0057702fde485c0165d6e8f13871c6bdf5c2a817e47215a501de1cf7f8d64308183fbca47bda7e1cbd30cc8f01

test:
  secret_key_base: 09ffc088d0aad1ac7cf8c650a5f16d98f89c013f047d28d09a27fa12048a6eef25d93c60245c07d5539b239c5f24d242d8ffd189ab1386af761bffeecbdc5a12

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
